"""Add Review Model

Revision ID: 1ba98557ff77
Revises: 56963bbe10a5
Create Date: 2024-05-09 19:11:53.951389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ba98557ff77'
down_revision = '56963bbe10a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
